FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
EXPOSE 80
# This Dockerfile sets up a simple web server using Nginx to serve an HTML file.
# The HTML file is copied to the appropriate directory in the Nginx container.